version: "3"

services:
  fincome-url-shortener-flask:
    build: .
    image: fincome-url-shortener
    ports:
      - "5000:5000"
    command: [ "flask", "run", "--host=${FLASK_HOST}" ]
    depends_on:
      fincome-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: password

  fincome-db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      interval: 20s
      retries: 5
      start_period: 3s
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      timeout: 5s
    volumes:
      - pg_data:/var/lib/postgresql/${POSTGRES_VERSION}/docker

volumes:
  pg_data: {}
